name: Workflow de testes do projeto

on:
  workflow_call:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [17]
        java-distribution: [temurin]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java-version }}
        distribution: ${{ matrix.java-distribution }}
    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven
      run: mvn --batch-mode clean test